import { Company } from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 1,
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=80&auto=format&fit=crop&q=60',
    code: 'COM-001',
    name: 'GreenBuild Properties Ltd.',
    type: 'Parent',
    industry: 'Real Estate',
    country: 'Bangladesh',
    countryFlag: '🇧🇩',
    city: 'Dhaka',
    phone: '+880 1711-123456',
    email: 'info@greenbuild.com',
    website: 'www.greenbuild.com',
    address: 'Plot 12, Road 11, Gulshan-2, Dhaka',
    branchesCount: 8,
    employeesCount: 320,
    status: 'Active',
    createdAt: '12 Jan 2025 09:00 AM',
  },
  {
    id: 2,
    logo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=80&auto=format&fit=crop&q=60',
    code: 'COM-002',
    name: 'Horizon Constructions LLC',
    type: 'Subsidiary',
    industry: 'Construction',
    country: 'Bangladesh',
    countryFlag: '🇧🇩',
    city: 'Dhaka',
    phone: '+880 1912-654321',
    email: 'contact@horizoncon.com',
    website: 'www.horizoncon.com',
    address: 'Level 5, Banani Commercial Complex, Dhaka',
    branchesCount: 5,
    employeesCount: 215,
    status: 'Active',
    createdAt: '20 Mar 2025 11:30 AM',
  },
  {
    id: 3,
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=80&auto=format&fit=crop&q=60',
    code: 'COM-003',
    name: 'Apex Finance Group',
    type: 'Joint Venture',
    industry: 'Finance',
    country: 'Bangladesh',
    countryFlag: '🇧🇩',
    city: 'Dhaka',
    phone: '+880 1855-789012',
    email: 'apex@apexfinance.bd',
    website: 'www.apexfinance.bd',
    address: 'Motijheel Commercial Area, Dhaka',
    branchesCount: 3,
    employeesCount: 185,
    status: 'Active',
    createdAt: '05 Jun 2025 02:15 PM',
  },
];
